
new_version: '0.1.21'

change_log: |
  - a change
  - second
  - third
  -fourth


release_body: |
  this is a release body giving the option of 
  describing the new release in more detail


## DO NOT CHANGE THIS MANUALLY
_MIN_COVERAGE: 85

