
new_version: '0.1.19'

change_log: |
  - test change
  - and another change


release_body: |
  this is a release body giving the option of 
  describing the new release in more detail


## DO NOT CHANGE THIS MANUALLY
_MIN_COVERAGE: '99'  

