  name: check_branch
  on:
    pull_request_target:
      branches: [main]
      
    workflow_dispatch:
  
  jobs:
    show_branch:
      runs-on: ubuntu-latest
      steps:
        - run: | 
            echo ${{github.ref}}
            echo $GITHUB_REF
            
            echo ${github.GITHUB_HEAD_REF}
            echo $GITHUB_HEAD_REF
            
            echo ${github.GITHUB_BASE_REF}
            echo $GITHUB_BASE_REF
            
            echo ${github.GITHUB_REF_NAME}
            echo $GITHUB_REF_NAME
            
            echo ${github.GITHUB_HEAD_REF}
            echo $GITHUB_HEAD_REF
        
  
    check_branch:
      runs-on: ubuntu-latest

      steps:
        - if: ${{ github.GITHUB_REF != 'dev' }}
          uses: superbrothers/close-pull-request@v3
          with:
            comment: Please re-open this PR against the dev branch. For more information, consult CONTRIBUTING.md.

        - run: echo PR against master that is not based on dev && exit 1

     
