  name: check_branch
  on:
    pull_request_target:
      branches:
        - main
      
    workflow_dispatch:

  jobs:
    show:
      runs-on: ubuntu-latest
      steps:
        - run: echo ${{ github.repository }} ${{ github.repository_owner }}
  
    wrong_branch:
      runs-on: ubuntu-latest
      if: ${{ github.head_ref != 'dev' }}
      
      steps:
        - uses: superbrothers/close-pull-request@v3
          with:
            comment: Please re-open this PR against the dev branch. For more information, consult CONTRIBUTING.md.
        - run: echo PR against master that is not based on dev && exit 1
        
