on:
  push:
    branches: 
      test_branch
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest cv_tests
 
  test-install:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build source distribution and wheel files
        run: python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Upload files to TestPyPI
        run: python -m twine upload --verbose --repository testpypi dist/* -u__token__ -p${{ secrets.TEST_PYPI_TOKEN }}

      - name: Install from test and run tests
        run: |
          echo "Will wait 10s" && sleep 10s
          pip install --no-cache-dir --index-url https://test.pypi.org/simple cvhero --no-deps
          pip install -r requirements.txt
          pytest cv_tests
          pip uninstall -y cvhero


