name: other

on:
  workflow_dispatch:

env:
  var: '12'
  
jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: latest_coverage
          path: OLDCOVER.txt
      - run: cat OLDCOVER.txt
        
  
