name: other

on:
  workflow_dispatch:
  workflow_call:

env:
  var: '12'
  
jobs:
  other_job:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ '' < '0.0.1' }}
        run: echo lower
      
      - if: ${{ '' > '0.0.1' }}
        run: echo greater
  
