name: other

on:
  workflow_dispatch:
  workflow_call:

env:
  var: '12'
  
jobs:
  other_job:
    runs-on: ubuntu-latest
    steps:
      - id: 'id1'
        run: echo "other job 1"
      
      - run: echo ${{ steps.id1.outputs.data }}
      
  other_job2:
    
    runs-on: ubuntu-latest
    steps:
      - run: echo "other job 2"
        
  
