name: other

on:
  workflow_dispatch:
  
  
jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world" > artifact.txt
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt
          
  download_artifact:
    needs: upload_artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
      - run: cat artifact.txt
      
      
  
