name: other

on:
  workflow_dispatch:

env:
  var: '12'
  
jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: latest_coverage
          workflow: trials.yml

      - run: cat OLDCOVER.txt
        
  
