name: other

on:
  workflow_dispatch:
  workflow_call:

env:
  var: '12'
  
jobs:
  other_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "other job 1"
    
  other_job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "other job 2"
        
  
