name: releaser
on:
  push:
    branches: [main]
      
env:
  NEWV: ''
  OLDV: ''
  OLDCOVER: '0'
        
jobs:
  # initialize:
  # runs-on: ubuntu-latest
  # 
  # steps:
  #   - run: echo "0" > OLDCOVER.txt
  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: latest_coverage
  #       path: OLDCOVER.txt     
  
  get_latest_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: get latest coverage
        uses: dawidd6/action-download-artifact@v2
        with:
          name: latest_coverage
          workflow: releaser.yml
      
      - name: set min coverage env
        run: | 
          echo "OLDCOVER=$(cat OLDCOVER.txt)" >> $GITHUB_ENV
          cat OLDCOVER.txt
        
      - if: ${{ env.OLDCOVER >= '99' }}
        run: echo 99 > OLDCOVER.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: min_coverage
          path: OLDCOVER.txt

  run_tests:
    needs: get_latest_coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
        
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: get min coverage
        uses: actions/download-artifact@v3
        with:
          name: min_coverage
      
      - name: set min coverage
        run: |
          echo "OLDCOVER=$(cat OLDCOVER.txt)" >> $GITHUB_ENV
          cat OLDCOVER.txt    
      
      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest coveralls
          pip install -r requirements.txt
          
      - name: run tests
        run: |
          echo testing with min coverage: $OLDCOVER
          # pytest --cov=cvhero --cov-fail-under=$OLDCOVER cv_tests > coverage.txt
          coverage run --source=cvhero -m pytest cv_tests
          coverage lcov -o coverage.lcov
      
      - name: coveralls parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: test_${{matrix.os}}_${{matrix.python-version}}
          parallel: true
          path-to-lcov: coverage.lcov
  
  finalize_tests:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: coveralls finalize
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{secrets.github_token}}
          parallel-finished: true
          path-to-lcov: coverage.lcov
      
  make_release:
    needs: finalize_tests
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: get_new_current_version
        run: | 
          echo "NEWV=$(grep "~" docs/change_log.rst -m1 -a1 | sed 1q | cut -d" " -f1)" >> $GITHUB_ENV
          echo "OLDV=$(grep "VERSION" -m1 setup.py | cut -d"=" -f2 | sed "s/['\" ]//g")" >> $GITHUB_ENV
          
      - name: verify
        if: ${{ env.NEWV == env.OLDV }}
        run: echo you did not update the change_log && exit 1
      
      - name: set version
        run: |  
            sed -i "s/$OLDV/$NEWV/" setup.py
            sed -i "s/$OLDV/$NEWV/" pyproject.toml
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Build Package
        run: python -m build
          
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN  }}
        
      - name: Install and run tests
        run: |
          echo "Will wait 30s" && sleep 30s
          pip install cvhero
          pip install -r requirements.txt
          pytest cv_tests
          pip uninstall -y cvhero
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: setup.py pyproject.toml
          commit_message: '[GH-Actions] updated verrsion numbers in setup.py and pyproject.toml'
          
      - name: Create Release  
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.NEWV }}
          tag_name: v${{ env.NEWV }}
    
    


  
