name: test_release
on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    
jobs:
  get_version_number:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: | 
          NEWV=$(grep "~" docs/change_log.rst -m1 -a1 | sed 1q | cut -d" " -f1)
          echo found version $NEWV
          
      - run: | 
          OLDV=$(grep "VERSION" -m1 setup.py | cut -d"=" -f2 | sed "s/['\" ]//g"
          echo current version $OLDV
