  name: test_release
  on:
    pull_request:
      branches: [main]
      
    workflow_dispatch:
    
  env:
    NEWV: ""
    OLDV: ""

  jobs:     
    check:
      runs-on: ubuntu-latest
      steps:
        - if: ${{ github.event.pull_request.head.repo.fork || github.head_ref != 'dev' }}
          run: echo PR against main that is not based on dev && exit 1

    run_tests:
      needs: check
      uses: ./.github/workflows/test_runner.yml
  
    test_new_release:
      needs: run_tests
      runs-on: ubuntu-latest  

      steps:
        - uses: actions/checkout@v3

        - name: get new_version 
          id: new_version
          uses: KJ002/read-yaml@1.6      
          with:
            file: .github/config_new_release.yml         
            key-path: '["new_version"]'
            
        - name: get_new_current_version
          run: | 
            echo "NEWV=${{ steps.new_version.outputs.data }}" >> $GITHUB_ENV
            echo "OLDV=$(grep "VERSION" -m1 setup.py | cut -d"=" -f2 | sed "s/['\" ]//g")" >> $GITHUB_ENV
            
        - name: warn_no_version
          if: ${{ env.NEWV <= env.OLDV }}
          uses: thollander/actions-comment-pull-request@v1
          with:
            message: WARNING - Version number in change_log is not incremented. Will not test release.
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    
        - name: exit_no_version
          if: ${{ env.NEWV <= env.OLDV }}
          run: echo you did not update the change_log && exit 1
        
        - name: make rc vnumber
          run: echo "NEWV=${{env.NEWV}}rc${{github.run_number}}.dev${{github.run_attempt}}" >> $GITHUB_ENV
        
        - name: set version
          run: |  
              echo release candidate: $NEWV
              sed -i "s/$OLDV/$NEWV/" setup.py
              sed -i "s/$OLDV/$NEWV/" pyproject.toml
              
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install build twine pytest
            cp cvhero/__init__.py oldinit.py
            echo 'print("DONWLOADED")' > cvhero/__init__.py && cat oldinit.py >> cvhero/__init__.py
            
        - name: Build source distribution and wheel files
          run: python -m build

        - name: Upload files to TestPyPI
          run: python -m twine upload --verbose --repository testpypi dist/* -u__token__ -p${{ secrets.TEST_PYPI_TOKEN }}

        - name: Install from testpypi
          continue-on-error: true
          run: |
            pip install --index-url https://test.pypi.org/simple cvhero==$NEWV --no-deps 
            while [ $? -gt 0 ]; do echo not found yet, sleeping 5s; sleep 5s; pip install --index-url https://test.pypi.org/simple cvhero==$NEWV --no-deps ; done
            
        - name: test new release
          run: | 
            pip install .
            python -c 'import cvhero;print(cvhero.__version__)'
            pytest cv_tests -s
            
