  name: test_release
  on:
    pull_request:
      branches: [main]
      
    workflow_dispatch:
    
  env:
    NEWV: ""
    OLDV: ""
    VALID: ${{ !github.event.pull_request.head.repo.fork && github.head_ref == 'dev' }}

  jobs:     
    run_tests:
      if: env.VALID
      uses: ./.github/workflows/test_runner.yml
  
    test_new_release:
      needs: run_tests
      runs-on: ubuntu-latest  

      steps:
        - uses: actions/checkout@v3

        - name: get new_version 
          id: new_version
          uses: KJ002/read-yaml@1.6      
          with:
            file: .github/config_new_release.yml         
            key-path: '["new_version"]'
            
        - name: get_new_current_version
          run: | 
            echo "NEWV=${{ steps.new_version.outputs.data }}" >> $GITHUB_ENV
            echo "OLDV=$(grep "VERSION" -m1 setup.py | cut -d"=" -f2 | sed "s/['\" ]//g")" >> $GITHUB_ENV
            
        - name: warn_no_version
          if: ${{ env.NEWV <= env.OLDV }}
          uses: thollander/actions-comment-pull-request@v1
          with:
            message: WARNING - Version number in change_log is not incremented. Will not test release.
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    
        - name: exit_no_version
          if: ${{ env.NEWV <= env.OLDV }}
          run: echo you did not update the change_log && exit 1

        - name: set version
          run: |  
              sed -i "s/$OLDV/$NEWV/" setup.py
              sed -i "s/$OLDV/$NEWV/" pyproject.toml
              
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build twine
            
        - name: Build source distribution and wheel files
          run: python -m build

        - name: Upload files to TestPyPI
          run: python -m twine upload --verbose --repository testpypi dist/* -u__token__ -p${{ secrets.TEST_PYPI_TOKEN }}

        - name: Install from test and run tests
          run: |
            echo "Will wait 30s" && sleep 30s
            pip install pip --upgrade
            pip install --index-url https://test.pypi.org/simple cvhero
            pip show cvhero
            pip install -r requirements.txt
            pytest cv_tests
            pip uninstall -y cvhero 
