name: trials

on:
  workflow_dispatch:
  
  
jobs:
  trial:
    runs-on: ubuntu-latest
    
    env:
      VAR: "text"
    
    steps:
      - run: | 
          echo $VAR
          echo ${{env.VAR}}
          echo "VAR=new text" >> $GITHUB_ENV
          
      - run: echo pass
        if: ${{env.VAR == 'new text'}}
        
      - run: echo fail
        if: ${{env.VAR != 'new text'}}
      
      - run: echo $VAR
        env:
          VAR: v${{ env.VAR }}
    
      - name: Create Release  
        id: v${{ env.VAR }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VAR }}
          release_name: Release v${{ env.VAR }}     
          body: | 
            Testing the release v${{ env.VAR }}
    
