name: trials

on:
  workflow_dispatch:
  
  
env:
  VAR: 3
  
jobs:
  trial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: prepare usage.rst
        continue-on-error: true
        run: |
          pip install cvhero==
          while [ $? -gt 0 ]; do echo not found yet, sleeping 5s; sleep 5s; pip install cvhero; done
            
      - run: python -c 'import cvhero; print(cvhero.__version__)
        
        
          
          

