name: trials

on:
  workflow_dispatch:
  
jobs:
  trial:
    runs-on: ubuntu-latest    
   
    env:
      NEWV: ''
      OLDV: ''
      SEP: '-------' # used to adjust the change_log
      NEW: ''
    
    steps:
      - uses: actions/checkout@v3
      - name: get new_version 
        id: new_version
        uses: KJ002/read-yaml@1.6      
        with:
          file: .github/config_new_release.yml         
          key-path: '["new_version"]'
      
      - name: get_new_current_version
        run: | 
          echo "NEWV=${{ steps.new_version.outputs.data }}" >> $GITHUB_ENV
          echo "OLDV=$(grep "VERSION" -m1 setup.py | cut -d"=" -f2 | sed "s/['\" ]//g")" >> $GITHUB_ENV
          
      - name: verify ${{env.NEWV}} > ${{env.OLDV}}
        if: ${{ env.NEWV <= env.OLDV }}
        run: echo you did not increment the version number && exit 1
            
      - name: set up new version
        run: |  
            sed -i "s/$OLDV/$NEWV/" setup.py
            sed -i "s/$OLDV/$NEWV/" pyproject.toml
                        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m/%d/%Y')"
      
      - run: echo ${{steps.date.outputs.date}}
      
      - name: Get changes
        id: changes
        uses: KJ002/read-yaml@1.6      
        with:
          file: .github/config_new_release.yml         
          key-path: '["change_log"]'        
      
      - name: show changes
        run: echo '${{ steps.changes.outputs.data }}'
            
      - name: create change log
        env:
          NEW: ${{ format('{0} ({1})\n~~~~~~~~~~~~~~\n{2}\n\n', env.NEWV, steps.date.outputs.date, steps.changes.outputs.data) }}
      
        run: | 
          sed -i "s/$SEP/$SEP\n$NEW\n/" docs/change_log.rst         
          
      
      - run: cat docs/change_log.rst
          
        
          
        
          
          

