name: trials

on:
  workflow_dispatch:
  
  
jobs:
  trial:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "0" > OLDCOVER.txt
      - uses: actions/upload-artifact@v3
        with:
          name: latest_coverage
          path: OLDCOVER.txt      
