name: trials

on:
  workflow_dispatch:
  
jobs:
  trial:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo run_id $GITHUB_RUN_ID
          echo run_number $GITHUB_RUN_NUMBER
          echo run_attempt $GITHUB_RUN_ATTEMPT
        
          
          

