name: trials

on:
  workflow_dispatch:
  
  
jobs:
  trial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: read yaml
        id: yaml-data
        uses: KJ002/read-yaml@1.6      
        with:
          file: .github/config_new_release.yml         
          key-path: '["new_release"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs }}"

