name: trials

on:
  workflow_dispatch:
  
  
env:
  VAR: 3
  
jobs:
  trial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: prepare usage.rst
        env:
          V: 0.2.1
          COMM: "pip index versions cvhero | grep 'LATEST:' | tr -s ' ' | cut -d' ' -f3"
        run: |
          pip install pip --upgrade
          while [ "$V" != $(eval "$COMM") ]; do echo not found yet, sleeping 5s; sleep 5s; done
            
      - run: python -c 'import cvhero; print(cvhero.__version__)'
        
        
          
          

